export 'authentication/authentication.dart';
export 'base/base.dart';
export 'detail_anime/detail_anime.dart';
export 'home/home.dart';
export 'my_list/my_list.dart';
export 'onboarding/onboarding.dart';
export 'profile/profile.dart';
export 'search/search.dart';
export 'detail_list_anime/detail_list_anime.dart';
