// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0R9_DLvzkxun8_EP0shTUOsa5AQqr3ks',
    appId: '1:72318015266:web:bcb58a086ad23ab7eab77b',
    messagingSenderId: '72318015266',
    projectId: 'wibupedia-id',
    authDomain: 'wibupedia-id.firebaseapp.com',
    storageBucket: 'wibupedia-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-T-OSkgL2aaHKphy0IoOnTkzZbG7by1k',
    appId: '1:72318015266:android:d63c5730c2850b24eab77b',
    messagingSenderId: '72318015266',
    projectId: 'wibupedia-id',
    storageBucket: 'wibupedia-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpwcQyKu5_4S0TfST_qJPgZK4kY2vrlUQ',
    appId: '1:72318015266:ios:63d96eda314445d5eab77b',
    messagingSenderId: '72318015266',
    projectId: 'wibupedia-id',
    storageBucket: 'wibupedia-id.appspot.com',
    androidClientId: '72318015266-7nvko0jbrtbirgj9j3aknivoa0n38udr.apps.googleusercontent.com',
    iosClientId: '72318015266-hg2vit7h8hhdj5ivomc5u83qvaf875o9.apps.googleusercontent.com',
    iosBundleId: 'id.wibupedia.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpwcQyKu5_4S0TfST_qJPgZK4kY2vrlUQ',
    appId: '1:72318015266:ios:63d96eda314445d5eab77b',
    messagingSenderId: '72318015266',
    projectId: 'wibupedia-id',
    storageBucket: 'wibupedia-id.appspot.com',
    androidClientId: '72318015266-7nvko0jbrtbirgj9j3aknivoa0n38udr.apps.googleusercontent.com',
    iosClientId: '72318015266-hg2vit7h8hhdj5ivomc5u83qvaf875o9.apps.googleusercontent.com',
    iosBundleId: 'id.wibupedia.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0R9_DLvzkxun8_EP0shTUOsa5AQqr3ks',
    appId: '1:72318015266:web:43eaa566a44da77feab77b',
    messagingSenderId: '72318015266',
    projectId: 'wibupedia-id',
    authDomain: 'wibupedia-id.firebaseapp.com',
    storageBucket: 'wibupedia-id.appspot.com',
  );
}
